/*
 * Test SOYYO
 * Test ingreso soyyo
 *
 * OpenAPI spec version: 1.0
 * Contact: neonacc@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Filter model module.
 * @module model/Filter
 * @version 1.0
 */
export class Filter {
  /**
   * Constructs a new <code>Filter</code>.
   * @alias module:model/Filter
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Filter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Filter} obj Optional instance to populate.
   * @return {module:model/Filter} The populated <code>Filter</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Filter();
      if (data.hasOwnProperty('startId'))
        obj.startId = ApiClient.convertToType(data['startId'], 'Number');
      if (data.hasOwnProperty('endId'))
        obj.endId = ApiClient.convertToType(data['endId'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} startId
 */
Filter.prototype.startId = undefined;

/**
 * @member {Number} endId
 */
Filter.prototype.endId = undefined;

