/*
 * Test SOYYO
 * Test ingreso soyyo
 *
 * OpenAPI spec version: 1.0
 * Contact: neonacc@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Entity} from '../model/Entity';
import {Error} from '../model/Error';
import {Filter} from '../model/Filter';

/**
* EntityFilter service.
* @module api/EntityFilterApi
* @version 1.0
*/
export class EntityFilterApi {

    /**
    * Constructs a new EntityFilterApi. 
    * @alias module:api/EntityFilterApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the entitiesFilterPost operation.
     * @callback moduleapi/EntityFilterApi~entitiesFilterPostCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Entity>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Filtrar listado entidades ordenadas alfabeticamente
     * Gets entities By name
     * @param {Object} opts Optional parameters
     * @param {module:model/Filter} opts.body Datos de entrada
     * @param {module:api/EntityFilterApi~entitiesFilterPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    entitiesFilterPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [Entity];

      return this.apiClient.callApi(
        '/entities/filter', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}