/*
 * Test SOYYO
 * Test ingreso soyyo
 *
 * OpenAPI spec version: 1.0
 * Contact: neonacc@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestSoyyo);
  }
}(this, function(expect, TestSoyyo) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Filter', function() {
      beforeEach(function() {
        instance = new TestSoyyo.Filter();
      });

      it('should create an instance of Filter', function() {
        // TODO: update the code to test Filter
        expect(instance).to.be.a(TestSoyyo.Filter);
      });

      it('should have the property startId (base name: "startId")', function() {
        // TODO: update the code to test the property startId
        expect(instance).to.have.property('startId');
        // expect(instance.startId).to.be(expectedValueLiteral);
      });

      it('should have the property endId (base name: "endId")', function() {
        // TODO: update the code to test the property endId
        expect(instance).to.have.property('endId');
        // expect(instance.endId).to.be(expectedValueLiteral);
      });

    });
  });

}));
