/*
 * Test SOYYO
 * Test ingreso soyyo
 *
 * OpenAPI spec version: 1.0
 * Contact: neonacc@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Entity} from './model/Entity';
import {Error} from './model/Error';
import {Filter} from './model/Filter';
import {EntityFilterApi} from './api/EntityFilterApi';

/**
* Test_ingreso_soyyo.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TestSoyyo = require('index'); // See note below*.
* var xxxSvc = new TestSoyyo.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TestSoyyo.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TestSoyyo.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TestSoyyo.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Entity model constructor.
     * @property {module:model/Entity}
     */
    Entity,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The Filter model constructor.
     * @property {module:model/Filter}
     */
    Filter,

    /**
    * The EntityFilterApi service constructor.
    * @property {module:api/EntityFilterApi}
    */
    EntityFilterApi
};
