/*
 * Test SOYYO
 * Test ingreso soyyo
 *
 * OpenAPI spec version: 1.0
 * Contact: neonacc@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TestSoyyo);
  }
}(this, function(expect, TestSoyyo) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TestSoyyo.EntityFilterApi();
  });

  describe('(package)', function() {
    describe('EntityFilterApi', function() {
      describe('entitiesFilterPost', function() {
        it('should call entitiesFilterPost successfully', function(done) {
          // TODO: uncomment, update parameter values for entitiesFilterPost call and complete the assertions
          /*
          var opts = {};

          instance.entitiesFilterPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(TestSoyyo.Entity);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
